USE ROLE ACCOUNTADMIN;
USE WAREHOUSE NYC_WH;
USE DATABASE NYC_TAXI_DB;
USE SCHEMA GOLD;


INSERT INTO GOLD.DIM_DATE
(
    DATE_KEY,
    FULL_DATE,
    YEAR,
    QUARTER,
    MONTH,
    MONTH_NAME,
    WEEK_OF_YEAR,
    DAY_OF_MONTH,
    DAY_NAME,
    DAY_OF_WEEK,
    IS_WEEKEND
)
WITH CALENDAR AS
(
    SELECT
        DATEADD(
            DAY,
            ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1,
            '2023-01-01'
        )::DATE AS FULL_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 365))
)

SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE,'YYYYMMDD')),
    FULL_DATE,
    YEAR(FULL_DATE),
    QUARTER(FULL_DATE),
    MONTH(FULL_DATE),
    MONTHNAME(FULL_DATE),
    WEEK(FULL_DATE),
    DAY(FULL_DATE),
    DAYNAME(FULL_DATE),
    DAYOFWEEKISO(FULL_DATE),
    IFF(
        DAYNAME(FULL_DATE) IN ('Sat','Sun'),
        TRUE,
        FALSE
    )
FROM CALENDAR;
