USE ROLE ACCOUNTADMIN;
USE WAREHOUSE NYC_WH;
USE DATABASE NYC_TAXI_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE DIM_LOCATION
(
    LOCATION_ID     NUMBER      NOT NULL,
    BOROUGH         STRING,
    ZONE            STRING,
    SERVICE_ZONE    STRING,

    LOAD_TIMESTAMP  TIMESTAMP_NTZ
);