INSERT INTO GOLD.DIM_LOCATION
(
    LOCATION_ID,
    BOROUGH,
    ZONE,
    SERVICE_ZONE,
    LOAD_TIMESTAMP
)

SELECT
    $1::NUMBER,
    $2::STRING,
    $3::STRING,
    $4::STRING,
    CURRENT_TIMESTAMP()
FROM @AUDIT.NYC_INTERNAL_STAGE/taxi_zone_lookup.csv
(
    FILE_FORMAT => 'AUDIT.NYC_CSV_FORMAT'
);