USE ROLE ACCOUNTADMIN;
USE WAREHOUSE NYC_WH;
USE DATABASE NYC_TAXI_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE FACT_TRIPS
(
    DATE_KEY                NUMBER NOT NULL,
    PICKUP_LOCATION_ID      NUMBER NOT NULL,
    DROPOFF_LOCATION_ID     NUMBER NOT NULL,
    PICKUP_DATETIME         TIMESTAMP_NTZ NOT NULL,
    DROPOFF_DATETIME        TIMESTAMP_NTZ NOT NULL,
    VENDOR_ID               NUMBER,
    RATE_CODE_ID            NUMBER,
    PAYMENT_TYPE            NUMBER,
    PASSENGER_COUNT         NUMBER,
    TRIP_DISTANCE           FLOAT,
    FARE_AMOUNT             NUMBER(10,2),
    EXTRA                   NUMBER(10,2),
    MTA_TAX                 NUMBER(10,2),
    TIP_AMOUNT              NUMBER(10,2),
    TOLLS_AMOUNT            NUMBER(10,2),
    IMPROVEMENT_SURCHARGE   NUMBER(10,2),
    TOTAL_AMOUNT            NUMBER(10,2),
    CONGESTION_SURCHARGE    NUMBER(10,2),
    AIRPORT_FEE             NUMBER(10,2),

    LOAD_TIMESTAMP          TIMESTAMP_NTZ,
    LOAD_BATCH_ID           STRING,
    RECORD_SOURCE           STRING
);