/*==============================================================================
Project      : NYC Taxi Analytics
Layer        : Gold
Script       : 03_merge_fact_trips.sql
Author       : Raju Nalla
Description  : Incrementally loads data from SILVER.TRIPS_STREAM into
               GOLD.FACT_TRIPS using MERGE.

Execution    : Scheduled / Incremental
Dependencies : SILVER.TRIPS_STREAM
==============================================================================*/

MERGE INTO GOLD.FACT_TRIPS AS TARGET

USING
(
    SELECT

        SHA2(
            CONCAT_WS('|',
                VENDORID,
                PICKUP_DATETIME,
                DROPOFF_DATETIME,
                PULOCATIONID,
                DOLOCATIONID,
                PAYMENT_TYPE,
                TOTAL_AMOUNT
            ),
        256) AS TRIP_HASH_KEY,

        TO_NUMBER(TO_CHAR(PICKUP_DATETIME,'YYYYMMDD')) AS DATE_KEY,

        PULOCATIONID AS PICKUP_LOCATION_ID,

        DOLOCATIONID AS DROPOFF_LOCATION_ID,

        PICKUP_DATETIME,
        DROPOFF_DATETIME,
        VENDORID       AS VENDOR_ID,
        RATECODEID     AS RATE_CODE_ID,
        PAYMENT_TYPE,
        PASSENGER_COUNT,
        TRIP_DISTANCE,
        FARE_AMOUNT,
        EXTRA,
        MTA_TAX,
        TIP_AMOUNT,
        TOLLS_AMOUNT,
        IMPROVEMENT_SURCHARGE,
        TOTAL_AMOUNT,
        CONGESTION_SURCHARGE,
        AIRPORT_FEE,
        LOAD_TIMESTAMP,
        LOAD_BATCH_ID,
        RECORD_SOURCE

    FROM SILVER.TRIPS_STREAM

) SOURCE

ON TARGET.TRIP_HASH_KEY = SOURCE.TRIP_HASH_KEY

WHEN MATCHED THEN
    UPDATE SET
        TARGET.DATE_KEY                 = SOURCE.DATE_KEY,
        TARGET.PICKUP_LOCATION_ID       = SOURCE.PICKUP_LOCATION_ID,
        TARGET.DROPOFF_LOCATION_ID      = SOURCE.DROPOFF_LOCATION_ID,
        TARGET.PICKUP_DATETIME          = SOURCE.PICKUP_DATETIME,
        TARGET.DROPOFF_DATETIME         = SOURCE.DROPOFF_DATETIME,
        TARGET.VENDOR_ID                = SOURCE.VENDOR_ID,
        TARGET.RATE_CODE_ID             = SOURCE.RATE_CODE_ID,
        TARGET.PAYMENT_TYPE             = SOURCE.PAYMENT_TYPE,
        TARGET.PASSENGER_COUNT          = SOURCE.PASSENGER_COUNT,
        TARGET.TRIP_DISTANCE            = SOURCE.TRIP_DISTANCE,
        TARGET.FARE_AMOUNT              = SOURCE.FARE_AMOUNT,
        TARGET.EXTRA                    = SOURCE.EXTRA,
        TARGET.MTA_TAX                  = SOURCE.MTA_TAX,
        TARGET.TIP_AMOUNT               = SOURCE.TIP_AMOUNT,
        TARGET.TOLLS_AMOUNT             = SOURCE.TOLLS_AMOUNT,
        TARGET.IMPROVEMENT_SURCHARGE    = SOURCE.IMPROVEMENT_SURCHARGE,
        TARGET.TOTAL_AMOUNT             = SOURCE.TOTAL_AMOUNT,
        TARGET.CONGESTION_SURCHARGE     = SOURCE.CONGESTION_SURCHARGE,
        TARGET.AIRPORT_FEE              = SOURCE.AIRPORT_FEE,
        TARGET.LOAD_TIMESTAMP           = CURRENT_TIMESTAMP(),
        TARGET.LOAD_BATCH_ID            = SOURCE.LOAD_BATCH_ID,
        TARGET.RECORD_SOURCE            = SOURCE.RECORD_SOURCE

WHEN NOT MATCHED THEN
INSERT
(
    TRIP_HASH_KEY,
    DATE_KEY,
    PICKUP_LOCATION_ID,
    DROPOFF_LOCATION_ID,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    VENDOR_ID,
    RATE_CODE_ID,
    PAYMENT_TYPE,
    PASSENGER_COUNT,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    LOAD_TIMESTAMP,
    LOAD_BATCH_ID,
    RECORD_SOURCE
)

VALUES
(
    SOURCE.TRIP_HASH_KEY,
    SOURCE.DATE_KEY,
    SOURCE.PICKUP_LOCATION_ID,
    SOURCE.DROPOFF_LOCATION_ID,
    SOURCE.PICKUP_DATETIME,
    SOURCE.DROPOFF_DATETIME,
    SOURCE.VENDOR_ID,
    SOURCE.RATE_CODE_ID,
    SOURCE.PAYMENT_TYPE,
    SOURCE.PASSENGER_COUNT,
    SOURCE.TRIP_DISTANCE,
    SOURCE.FARE_AMOUNT,
    SOURCE.EXTRA,
    SOURCE.MTA_TAX,
    SOURCE.TIP_AMOUNT,
    SOURCE.TOLLS_AMOUNT,
    SOURCE.IMPROVEMENT_SURCHARGE,
    SOURCE.TOTAL_AMOUNT,
    SOURCE.CONGESTION_SURCHARGE,
    SOURCE.AIRPORT_FEE,
    SOURCE.LOAD_TIMESTAMP,
    SOURCE.LOAD_BATCH_ID,
    SOURCE.RECORD_SOURCE
);