USE ROLE ACCOUNTADMIN;
USE WAREHOUSE NYC_WH;
USE DATABASE NYC_TAXI_DB;
USE SCHEMA AUDIT;

-- Create Parquet File Format
CREATE OR REPLACE FILE FORMAT NYC_PARQUET_FORMAT
TYPE = PARQUET
COMPRESSION = AUTO;

-- Verify
SHOW FILE FORMATS;

DESC FILE FORMAT NYC_PARQUET_FORMAT;
