USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR NYC_RESOURCE_MONITOR
WITH CREDIT_QUOTA = 10
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS
ON 75 PERCENT DO NOTIFY
ON 90 PERCENT DO SUSPEND
ON 100 PERCENT DO SUSPEND_IMMEDIATE;


ALTER WAREHOUSE NYC_WH
SET RESOURCE_MONITOR = NYC_RESOURCE_MONITOR;

SHOW RESOURCE MONITORS;