



----final code 

INSERT INTO SILVER.TRIPS
(
    VENDORID,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    PASSENGER_COUNT,
    RATECODEID,
    STORE_AND_FWD_FLAG,
    PULOCATIONID,
    DOLOCATIONID,
    PAYMENT_TYPE,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    LOAD_TIMESTAMP,
    ETL_UPDATED_TIMESTAMP,
    SOURCE_FILE_NAME,
    LOAD_BATCH_ID,
    RECORD_SOURCE
)
SELECT
    VENDORID,
    TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000) AS PICKUP_DATETIME,
    TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000) AS DROPOFF_DATETIME,
    PASSENGER_COUNT::NUMBER,
    RATECODEID::NUMBER,
    STORE_AND_FWD_FLAG,
    PULOCATIONID,
    DOLOCATIONID,
    PAYMENT_TYPE,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP() AS ETL_UPDATED_TIMESTAMP,
    SOURCE_FILE_NAME,
    LOAD_BATCH_ID,
    RECORD_SOURCE
FROM BRONZE.RAW_TRIPS
WHERE
VENDORID IS NOT NULL
AND TPEP_PICKUP_DATETIME IS NOT NULL
AND TPEP_DROPOFF_DATETIME IS NOT NULL
AND PULOCATIONID IS NOT NULL
AND DOLOCATIONID IS NOT NULL
AND PAYMENT_TYPE IS NOT NULL
AND TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000)
    BETWEEN '2023-01-01'::TIMESTAMP_NTZ
        AND '2023-12-31 23:59:59'::TIMESTAMP_NTZ
AND TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000)
    BETWEEN '2023-01-01'::TIMESTAMP_NTZ
        AND '2023-12-31 23:59:59'::TIMESTAMP_NTZ
AND TRIP_DISTANCE > 0
AND FARE_AMOUNT > 0
AND TOTAL_AMOUNT > 0
AND TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000)
    < TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000);