-- Record Count
SELECT COUNT(*) FROM BRONZE.RAW_TRIPS;
SELECT COUNT(*) FROM SILVER.TRIPS;
SELECT COUNT(*) FROM GOLD.FACT_TRIPS;

-- Month-wise Validation
SELECT
    TO_CHAR(PICKUP_DATETIME,'YYYY-MM'),
    COUNT(*)
FROM SILVER.TRIPS
GROUP BY 1
ORDER BY 1;

-- Null Validation
SELECT COUNT(*)
FROM SILVER.TRIPS
WHERE VENDORID IS NULL;