MERGE INTO GOLD.FACT_TRIPS AS TARGET
USING SILVER.VW_TRIPS_TRANSFORMED AS SOURCE
ON TARGET.TRIP_HASH_KEY = SOURCE.TRIP_HASH_KEY

WHEN MATCHED THEN
UPDATE SET
    TARGET.LOAD_TIMESTAMP = SOURCE.LOAD_TIMESTAMP,
    TARGET.LOAD_BATCH_ID  = SOURCE.LOAD_BATCH_ID,
    TARGET.RECORD_SOURCE  = SOURCE.RECORD_SOURCE
    WHEN NOT MATCHED THEN
INSERT
(
    TRIP_HASH_KEY,
    DATE_KEY,
    PICKUP_LOCATION_ID,
    DROPOFF_LOCATION_ID,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    VENDOR_ID,
    RATE_CODE_ID,
    PAYMENT_TYPE,
    PASSENGER_COUNT,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    LOAD_TIMESTAMP,
    LOAD_BATCH_ID,
    RECORD_SOURCE
)
VALUES
(
    SOURCE.TRIP_HASH_KEY,
    SOURCE.DATE_KEY,
    SOURCE.PICKUP_LOCATION_ID,
    SOURCE.DROPOFF_LOCATION_ID,
    SOURCE.PICKUP_DATETIME,
    SOURCE.DROPOFF_DATETIME,
    SOURCE.VENDOR_ID,
    SOURCE.RATE_CODE_ID,
    SOURCE.PAYMENT_TYPE,
    SOURCE.PASSENGER_COUNT,
    SOURCE.TRIP_DISTANCE,
    SOURCE.FARE_AMOUNT,
    SOURCE.EXTRA,
    SOURCE.MTA_TAX,
    SOURCE.TIP_AMOUNT,
    SOURCE.TOLLS_AMOUNT,
    SOURCE.IMPROVEMENT_SURCHARGE,
    SOURCE.TOTAL_AMOUNT,
    SOURCE.CONGESTION_SURCHARGE,
    SOURCE.AIRPORT_FEE,
    SOURCE.LOAD_TIMESTAMP,
    SOURCE.LOAD_BATCH_ID,
    SOURCE.RECORD_SOURCE
);