INSERT INTO GOLD.DIM_LOCATION
(
    LOCATION_ID,
    LOAD_TIMESTAMP
)

SELECT
    LOCATION_ID,
    CURRENT_TIMESTAMP()
FROM
(
    SELECT DISTINCT PULOCATIONID AS LOCATION_ID
    FROM SILVER.TRIPS

    UNION

    SELECT DISTINCT DOLOCATIONID AS LOCATION_ID
    FROM SILVER.TRIPS
);