INSERT INTO GOLD.FACT_TRIPS
(
    TRIP_HASH_KEY,
    DATE_KEY,
    PICKUP_LOCATION_ID,
    DROPOFF_LOCATION_ID,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    VENDOR_ID,
    RATE_CODE_ID,
    PAYMENT_TYPE,
    PASSENGER_COUNT,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    LOAD_TIMESTAMP,
    LOAD_BATCH_ID,
    RECORD_SOURCE
)

SELECT
SHA2(
    CONCAT_WS('|',
        S.VENDORID,
        S.PICKUP_DATETIME,
        S.DROPOFF_DATETIME,
        S.PULOCATIONID,
        S.DOLOCATIONID,
        S.PAYMENT_TYPE,
        S.TOTAL_AMOUNT
    ),
256) AS TRIP_HASH_KEY,
D.DATE_KEY,
LP.location_id AS PICKUP_LOCATION_ID,
LD.location_id as DROPOFF_LOCATION_ID,
S.PICKUP_DATETIME,
S.DROPOFF_DATETIME,
S.VENDORID,
S.RATECODEID,
S.PAYMENT_TYPE,
S.PASSENGER_COUNT,
S.TRIP_DISTANCE,
S.FARE_AMOUNT,
S.EXTRA,
S.MTA_TAX,
S.TIP_AMOUNT,
S.TOLLS_AMOUNT,
S.IMPROVEMENT_SURCHARGE,
S.TOTAL_AMOUNT,
S.CONGESTION_SURCHARGE,
S.AIRPORT_FEE,
CURRENT_TIMESTAMP(),
S.LOAD_BATCH_ID,
S.RECORD_SOURCE
FROM SILVER.TRIPS S
INNER JOIN GOLD.DIM_DATE D
ON CAST(S.PICKUP_DATETIME AS DATE)=D.FULL_DATE
INNER JOIN GOLD.DIM_LOCATION LP
ON S.PULOCATIONID=LP.LOCATION_ID
INNER JOIN GOLD.DIM_LOCATION LD
ON S.DOLOCATIONID=LD.LOCATION_ID;