USE ROLE ACCOUNTADMIN;
USE WAREHOUSE NYC_WH;
USE DATABASE NYC_TAXI_DB;
USE SCHEMA GOLD;

INSERT INTO GOLD.FACT_TRIPS
(
    DATE_KEY,
    PICKUP_LOCATION_ID,
    DROPOFF_LOCATION_ID,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    VENDOR_ID,
    RATE_CODE_ID,
    PAYMENT_TYPE,
    PASSENGER_COUNT,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    EXTRA,
    MTA_TAX,
    TIP_AMOUNT,
    TOLLS_AMOUNT,
    IMPROVEMENT_SURCHARGE,
    TOTAL_AMOUNT,
    CONGESTION_SURCHARGE,
    AIRPORT_FEE,
    LOAD_TIMESTAMP,
    LOAD_BATCH_ID,
    RECORD_SOURCE
)

WITH TRIPS_DATA AS
(
    SELECT
        TO_NUMBER(TO_CHAR(PICKUP_DATETIME,'YYYYMMDD')) AS DATE_KEY,
        PULOCATIONID,
        DOLOCATIONID,
        PICKUP_DATETIME,
        DROPOFF_DATETIME,
        VENDORID,
        RATECODEID,
        PAYMENT_TYPE,
        PASSENGER_COUNT,
        TRIP_DISTANCE,
        FARE_AMOUNT,
        EXTRA,
        MTA_TAX,
        TIP_AMOUNT,
        TOLLS_AMOUNT,
        IMPROVEMENT_SURCHARGE,
        TOTAL_AMOUNT,
        CONGESTION_SURCHARGE,
        AIRPORT_FEE,
        CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP,
        LOAD_BATCH_ID,
        RECORD_SOURCE
    FROM SILVER.TRIPS
)

SELECT
    T.DATE_KEY,
    PL.LOCATION_ID,
    DL.LOCATION_ID,
    T.PICKUP_DATETIME,
    T.DROPOFF_DATETIME,
    T.VENDORID,
    T.RATECODEID,
    T.PAYMENT_TYPE,
    T.PASSENGER_COUNT,
    T.TRIP_DISTANCE,
    T.FARE_AMOUNT,
    T.EXTRA,
    T.MTA_TAX,
    T.TIP_AMOUNT,
    T.TOLLS_AMOUNT,
    T.IMPROVEMENT_SURCHARGE,
    T.TOTAL_AMOUNT,
    T.CONGESTION_SURCHARGE,
    T.AIRPORT_FEE,
    T.LOAD_TIMESTAMP,
    T.LOAD_BATCH_ID,
    T.RECORD_SOURCE
FROM TRIPS_DATA T
INNER JOIN GOLD.DIM_DATE D
    ON T.DATE_KEY = D.DATE_KEY
INNER JOIN GOLD.DIM_LOCATION PL
    ON T.PULOCATIONID = PL.LOCATION_ID
INNER JOIN GOLD.DIM_LOCATION DL
    ON T.DOLOCATIONID = DL.LOCATION_ID;