--1. Duplicate Check

SELECT
    DATE_KEY,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    PICKUP_LOCATION_ID,
    DROPOFF_LOCATION_ID,
    COUNT(*) AS CNT
FROM GOLD.FACT_TRIPS
GROUP BY
    DATE_KEY,
    PICKUP_DATETIME,
    DROPOFF_DATETIME,
    PICKUP_LOCATION_ID,
    DROPOFF_LOCATION_ID
HAVING COUNT(*) > 1;

--2. Negative Values Check

SELECT
COUNT_IF(TRIP_DISTANCE < 0) AS NEG_DISTANCE,
COUNT_IF(FARE_AMOUNT < 0) AS NEG_FARE,
COUNT_IF(TOTAL_AMOUNT < 0) AS NEG_TOTAL
FROM GOLD.FACT_TRIPS;

--3. Passenger Count Validation

SELECT
MIN(PASSENGER_COUNT),
MAX(PASSENGER_COUNT)
FROM GOLD.FACT_TRIPS;


--4. Date Range Validation
SELECT
MIN(PICKUP_DATETIME),
MAX(PICKUP_DATETIME)
FROM GOLD.FACT_TRIPS;

--5. Missing Location Validation

SELECT
COUNT(*)
FROM GOLD.FACT_TRIPS F
LEFT JOIN GOLD.DIM_LOCATION L
ON F.PICKUP_LOCATION_ID = L.LOCATION_ID
WHERE L.LOCATION_ID IS NULL;

--6. Missing Date Validation
SELECT
COUNT(*)
FROM GOLD.FACT_TRIPS F
LEFT JOIN GOLD.DIM_DATE D
ON F.DATE_KEY = D.DATE_KEY
WHERE D.DATE_KEY IS NULL;

--7. Null Measure Validation    
SELECT

COUNT_IF(TRIP_DISTANCE IS NULL),
COUNT_IF(FARE_AMOUNT IS NULL),
COUNT_IF(TOTAL_AMOUNT IS NULL)

FROM GOLD.FACT_TRIPS;

--8. Batch Validation

SELECT
LOAD_BATCH_ID,
COUNT(*)
FROM GOLD.FACT_TRIPS
GROUP BY LOAD_BATCH_ID; 

--9. Source Validation

SELECT
RECORD_SOURCE,
COUNT(*)
FROM GOLD.FACT_TRIPS
GROUP BY RECORD_SOURCE;

--10. Referential Integrity Check   

SELECT COUNT(*)
FROM GOLD.FACT_TRIPS
WHERE PICKUP_LOCATION_ID NOT IN
(
SELECT LOCATION_ID
FROM GOLD.DIM_LOCATION
);